on:
  pull_request:
    branches:
      - 'master'
    types:
      - closed
env:
  LOGIN: ${{ secrets.DOCKER_LOGIN }}
  PASSWORD: ${{ secrets.DOCKER_PWD }}
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: [ubuntu-latest]

    steps:
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ env.LOGIN }}
          password: ${{ env.PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build images
        run: |
          docker build -t "${{ env.LOGIN }}/multi-api:"${GITHUB_REF##*/} -f ./api/Dockerfile ./api
          docker build -t "${{ env.LOGIN }}/multi-auth:"${GITHUB_REF##*/} -f ./auth/Dockerfile ./auth
          docker build -t "${{ env.LOGIN }}/multi-frontend:"${GITHUB_REF##*/} -f ./frontend/Dockerfile.prod ./frontend
      - name: Push images to docker.io
        run: |
          docker push "${{ env.LOGIN }}/multi-api:"${GITHUB_REF##*/}
          docker push "${{ env.LOGIN }}/multi-auth:"${GITHUB_REF##*/}
          docker push "${{ env.LOGIN }}/multi-frontend:"${GITHUB_REF##*/}